name: Build and Push Gatus Image

on:
  push:
    branches:
      - master
    paths: 
      - 'GatusApp/**'
      - '.github/workflows/**'

jobs: 
  build-and-push-ECR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v3
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build the Docker Image
        run: |
          docker build -t gatus ./GatusApp

      - name: Tag Docker Image (Needs to be tagged with ECR URI for push)
        run: |
          docker tag gatus:latest ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker Image onto ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest 