name: terraform apply (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read
  id-token: write


jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./terraform


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Download plan artifact from latest Plan run
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: terraformworkflow.yml
          workflow_conclusion: success
          branch: master
          name: tf-plan         
          path: ./terraform
          if_no_artifact_found: fail

      - name: Re-anitialize
        run: terraform init -input=false

      - name: Apply approved plan
        run: terraform apply -input=false -auto-approve plan.out