name: terraform destroy (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read
  id-token: write


jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./terraform


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-east-1
      
      - name: Destroy infra 
        run: |
          terraform init
          terraform destroy -auto-approve
