name: plan terraform changes

on:
  push:
    branches:
      - master
    paths:
      - terraform/**
      - '.github/workflows/**'

jobs:
  applying-terraform-changes:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Installing terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v3
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Initialize the terraform state file
        working-directory: ./terraform
        run: |
          terraform fmt -check -recursive
          terraform init 
          terraform validate

      - name: Run the terraform plan
        working-directory: ./terraform
        run: |
          terraform plan


      - name: Plan
        run: |
          terraform plan -no-color
          terraform show -no-color plan.out > plan.txt


      - name: Show plan in job summary
        run: |
          {
            echo '## Terraform Plan'
            echo ''
            echo '```'
            sed -n '1,400p' plan.txt
            echo '```'
            echo ''
            echo '_Full plan attached as an artifact (tf-plan)._'
          } >> "$GITHUB_STEP_SUMMARY"

          
